### ISSUE TITLE
Multiplatform artifacts

### ISSUE THREAD

**Issue by ubuntudroid** [cvb941/kotlin-parallel-collection-operations#1]
It would be great if this library would also be usable in multiplatform projects by adding artifacts for `iosArm64`, `iosSimulator` and `iosX64` and the likes.

**Comment by cvb941** [comment]
Hello, this is the next step of this library and will get done at _some_ point.

**Comment by ubuntudroid** [comment]
Awesome, looking forward to it, thanks for your efforts! 🙏

**Comment by cvb941** [comment]
Since latest 2.0.0 release, the library is now multiplatform. Please let know in case you encounter any issues if you are still interested in the library and try it out :)
